/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#00dbe7",
        "primary": "#e1fdff",
        "primary-container": "#00f2ff",
        "secondary": "#bbc3ff",
        "secondary-container": "#0231de",
        "tertiary-fixed-dim": "#d1bcff",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "background": "#0c1322",
        "surface": "#0c1322",
        "surface-dim": "#0c1322",
        "surface-variant": "#2e3445",
        "surface-container-lowest": "#070e1d",
        "surface-container-low": "#151b2b",
        "surface-container": "#191f2f",
        "surface-container-high": "#232a3a",
        "surface-container-highest": "#2e3445",
        "surface-bright": "#32394a",
        "on-background": "#dce2f8",
        "on-surface": "#dce2f8",
        "on-surface-variant": "#b9cacb",
        "on-primary": "#00363a",
        "on-primary-container": "#006a71",
        "on-secondary-container": "#b1bbff",
        "on-tertiary": "#3c0090",
        "outline": "#849495",
        "outline-variant": "#3a494b",
      },
      fontFamily: {
        data: ['Geist', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        headline: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
